"""add share fields

Revision ID: 0003
Revises: 0002
Create Date: 2025-01-14 22:10:00.000000
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Set default value for existing rows
    op.execute("UPDATE chats SET is_public = false WHERE is_public IS NULL")
    # Make it not nullable
    op.alter_column("chats", "is_public", existing_type=sa.Boolean(), nullable=False)

    # Add unique index to public_share_id (it already exists as a column)
    op.create_index(
        op.f("ix_chats_public_share_id"), "chats", ["public_share_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chats_public_share_id"), table_name="chats")
    op.alter_column("chats", "is_public", existing_type=sa.Boolean(), nullable=True)
    # ### end Alembic commands ###